### ISSUE TITLE
Missing dev files when building on Ubuntu

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#462]
After running prerequisites and running make release. It fails to find the header files installed in the previous step. 

I have to manually install all the Ubuntu dev files manually

ie

```
In file included from projects/publishers/./file/file_session.h:5,
                 from projects/publishers/./file/file_stream.h:8,
                 from projects/publishers/./file/file_application.h:7,
                 from projects/publishers/./file/file_publisher.h:9,
                 from projects/publishers/publishers.h:14,
                 from projects/api_server/controllers/v1/vhosts/apps/app_actions_controller.cpp:16:
projects/modules/file/file_writer.h:8:10: fatal error: libavcodec/avcodec.h: No such file or directory
    8 | #include <libavcodec/avcodec.h>
 ```

**Comment by danrossi** [comment]
I tried the "manual" process and I get 

```
nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.
```

I tried installing on Debian WSL , I managed to get it all built after manually finding the SRT package, the service runs but no ports seem to open up.

**Comment by getroot** [comment]
What version of Ubuntu did you use?
I've never seen a case where avcodec.h was not found after prerequisites.sh succeeded so far.
Does /opt/ovenmediaengine/inlcude/libavcodec exist after running prerequisites.sh?

**Comment by danrossi** [comment]
I'm going through the manual process and srtp2 fails, although I installed it as a ubuntu package already. Does it need to be built from source ? 

```
configure: WARNING: unrecognized options: --enable-shared, --disable-static
gcc -shared -o libsrtp2.so.1 -shared -Wl,-soname,libsrtp2.so.1 \
                        srtp/srtp.o srtp/ekt.o crypto/cipher/cipher.o crypto/cipher/null_cipher.o crypto/cipher/aes_icm_ossl.o crypto/cipher/aes_gcm_ossl.o crypto/hash/null_auth.o crypto/hash/auth.o crypto/hash/hmac_ossl.o crypto/math/datatypes.o crypto/math/stat.o crypto/kernel/crypto_kernel.o crypto/kernel/alloc.o crypto/kernel/key.o crypto/kernel/err.o crypto/replay/rdb.o crypto/replay/rdbx.o crypto/replay/ut_sim.o -L. -L/opt/ovenmediaengine/lib -L/usr/local/lib -lcrypto
/usr/bin/ld: /usr/local/lib/libcrypto.a(mem.o): relocation R_X86_64_PC32 against symbol `CRYPTO_malloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:141: libsrtp2.so.1] Error 1
```

**Comment by danrossi** [comment]
I'm using Ubuntu 20.04

**Comment by getroot** [comment]
I've confirmed that it works well on ubuntu 20.04, but I'll check again later.
If a package doesn't get installed when doing a manual install, it might be a good idea to ask the community for that package.

**Comment by danrossi** [comment]
this manual command fails. I got the others working apart from srtp2 will try another build

```
PREFIX=/opt/ovenmediaengine && \
> JEMALLOC_VERSION=5.2.1 && \
> DIR=${TEMP_PATH}/jemalloc && \
> mkdir -p ${DIR} && \
> cd ${DIR} && \
> curl -sLf https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VERSION}/jemalloc-${JEMALLOC_VERSION}.tar.bz2 | tar -jx --strip-components=1 && \
> ./configure --prefix="${PREFIX}" && \
> make && \
> sudo make install_include install_lib && \
> rm -rf ${DIR}
mkdir: cannot create directory ‘/jemalloc’: Permission denied

```

**Comment by getroot** [comment]
> mkdir: cannot create directory ‘/jemalloc’: Permission denied

Change `> DIR=${TEMP_PATH}/jemalloc && \` to > DIR=/tmp/jemalloc && \

**Comment by danrossi** [comment]
So strange. I've never had a problem building SRT before. But I ran into such problem. hopefully using the Ubuntu packages is ok

```
/usr/bin/ld: /usr/local/lib/libcrypto.a(p5_crpt2.o): relocation R_X86_64_PC32 against symbol `PBE2PARAM_it' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/srt_shared.dir/build.make:140: libsrt.so.1.3.3] Error 1
make[1]: *** [CMakeFiles/Makefile2:227: CMakeFiles/srt_shared.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by danrossi** [comment]
I fully installed ffmpeg using the manual command but it still complains of missing headers

```
In file included from projects/publishers/./file/file_session.h:5,
                 from projects/publishers/./file/file_stream.h:8,
                 from projects/publishers/./file/file_application.h:7,
                 from projects/publishers/./file/file_publisher.h:9,
                 from projects/publishers/publishers.h:14,
                 from projects/api_server/controllers/v1/vhosts/apps/app_actions_controller.cpp:16:
projects/modules/file/file_writer.h:9:10: fatal error: libavformat/avformat.h: No such file or directory
    9 | #include <libavformat/avformat.h>
    ```

**Comment by getroot** [comment]
Manual installation is very difficult to troubleshoot, so I will check if prerequisites.sh works in ubuntu 20.04.

**Comment by danrossi** [comment]
4 times installing ffmpeg manually,  I now get headers showing up but the build still fails to find them

```
drwxr-xr-x 1 root root  4096 Aug  5 15:09 fdk-aac
drwxr-xr-x 1 root root  4096 Aug  5 15:20 jemalloc
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libavcodec
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libavfilter
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libavformat
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libavutil
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libpostproc
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libswresample
drwxr-xr-x 1 root root  4096 Aug  5 15:28 libswscale
drwxr-xr-x 1 root root  4096 Aug  5 15:11 opus
-rw-r--r-- 1 root root 47120 Aug  5 14:43 pcre2.h
-rw-r--r-- 1 root root  6677 Aug  5 14:43 pcre2posix.h
drwxr-xr-x 1 root root  4096 Aug  5 15:13 vpx
-rw-r--r-- 1 root root 46889 Aug  5 15:14 x264.h
-rw-r--r-- 1 root root   172 Aug  5 15:14 x264_config.h
```

```
In file included from projects/publishers/./file/file_session.h:5,
                 from projects/publishers/./file/file_stream.h:8,
                 from projects/publishers/./file/file_application.h:7,
                 from projects/publishers/./file/file_publisher.h:9,
                 from projects/publishers/publishers.h:14,
                 from projects/api_server/controllers/v1/vhosts/apps/app_actions_controller.cpp:16:
projects/modules/file/file_writer.h:9:10: fatal error: libavformat/avformat.h: No such file or directory
    9 | #include <libavformat/avformat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
      
 ```

**Comment by danrossi** [comment]
I've actually spent 2 days trying to get this built and only need it for WebRTC player integration development. Is there binaries for Ubuntu ? Ive spent 2 hours trying to get includes working. I tried added the include path to the CC include variable and still not working

```
PROJECT_C_INCLUDES := \
	projects \
	projects/third_party \
	/opt/ovenmediaengine/lib/include
```

**Comment by getroot** [comment]
With the information given to me, I can't figure out why prerequisites.sh is failing in your environment. We have experience using prerequisites.sh to install and use ubuntu 20.04 normally. What makes your environment different from those of others?

It is recommended to use docker image first. https://airensoft.gitbook.io/ovenmediaengine/getting-started#running-with-docker

**Comment by danrossi** [comment]
This modification inside AMK.mk works adding include path to c / c++ include paths. Not sure what is going on with pkgconfig as the include path is generated there also

```
LOCAL_PATH := $(call get_local_path)

PROJECT_C_INCLUDES := \
	projects \
	projects/third_party \
	/opt/ovenmediaengine/include

PROJECT_CXX_INCLUDES := \
	$(PROJECT_C_INCLUDES)

# -Wfatal-errors: build 중 첫 번째 오류를 만나면 멈춤
PROJECT_CFLAGS := \
	-D__STDC_CONSTANT_MACROS \
	-Wfatal-errors \
	-Wno-unused-function \
	-I/opt/ovenmediaengine/include

PROJECT_CXXFLAGS := \
	$(PROJECT_CFLAGS) \
	-Wliteral-suffix \
	-std=c++17 \
	-I/opt/ovenmediaengine/include

PROJECT_LDFLAGS := \
	-ldl -lz

include $(CLEAR_VARIABLES)
include $(BUILD_SUB_AMS)
```

**Comment by getroot** [comment]
You don't need to edit the AMK.mk file (no one installs OME like that). And you don't need to modify anything else in OME. Since OME is installed and used normally in many environments, finding out what is different in your environment and solving it is the right solution.

Use Docker. You can launch OME with a single command line.

**Comment by danrossi** [comment]
SSL fails because the manual build script installs in the wrong prefix. Will try and fix that. 

```
[  2/352|  0%] [static] libovcrypto.a: C++ projects/base/ovcrypto/certificate.cpp => intermediates/RELEASE/objs/base/ovcrypto/certificate.o
projects/base/ovcrypto/certificate.cpp:3:10: fatal error: openssl/core_names.h: No such file or directory
    3 | #include <openssl/core_names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
 ```
 
 ie
 
 ```
 install ./include/openssl/whrlpool.h -> /usr/local/include/openssl/whrlpool.h
install ./include/openssl/x509.h -> /usr/local/include/openssl/x509.h
install ./include/openssl/x509_vfy.h -> /usr/local/include/openssl/x509_vfy.h
install ./include/openssl/x509v3.h -> /usr/local/include/openssl/x509v3.h

```

**Comment by getroot** [comment]
Gee... it's not wrong...
OME installs openssl in /opt/ovenmediaengine/ to avoid conflicts with the pre-installed openssl.

**Comment by getroot** [comment]
> This modification inside AMK.mk works adding include path to c / c++ include paths. Not sure what is going on with pkgconfig as the include path is generated there also
> 
> ```
> LOCAL_PATH := $(call get_local_path)
> 
> PROJECT_C_INCLUDES := \
> 	projects \
> 	projects/third_party \
> 	/opt/ovenmediaengine/include
> 
> PROJECT_CXX_INCLUDES := \
> 	$(PROJECT_C_INCLUDES)
> 
> # -Wfatal-errors: build 중 첫 번째 오류를 만나면 멈춤
> PROJECT_CFLAGS := \
> 	-D__STDC_CONSTANT_MACROS \
> 	-Wfatal-errors \
> 	-Wno-unused-function \
> 	-I/opt/ovenmediaengine/include
> 
> PROJECT_CXXFLAGS := \
> 	$(PROJECT_CFLAGS) \
> 	-Wliteral-suffix \
> 	-std=c++17 \
> 	-I/opt/ovenmediaengine/include
> 
> PROJECT_LDFLAGS := \
> 	-ldl -lz
> 
> include $(CLEAR_VARIABLES)
> include $(BUILD_SUB_AMS)
> ```



> This modification inside AMK.mk works adding include path to c / c++ include paths. Not sure what is going on with pkgconfig as the include path is generated there also
> 
> ```
> LOCAL_PATH := $(call get_local_path)
> 
> PROJECT_C_INCLUDES := \
> 	projects \
> 	projects/third_party \
> 	/opt/ovenmediaengine/include
> 
> PROJECT_CXX_INCLUDES := \
> 	$(PROJECT_C_INCLUDES)
> 
> # -Wfatal-errors: build 중 첫 번째 오류를 만나면 멈춤
> PROJECT_CFLAGS := \
> 	-D__STDC_CONSTANT_MACROS \
> 	-Wfatal-errors \
> 	-Wno-unused-function \
> 	-I/opt/ovenmediaengine/include
> 
> PROJECT_CXXFLAGS := \
> 	$(PROJECT_CFLAGS) \
> 	-Wliteral-suffix \
> 	-std=c++17 \
> 	-I/opt/ovenmediaengine/include
> 
> PROJECT_LDFLAGS := \
> 	-ldl -lz
> 
> include $(CLEAR_VARIABLES)
> include $(BUILD_SUB_AMS)
> ```

What you are trying to do is already defined at https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/core/config.mk#L36

If it's a clean Ubuntu 20.04, prerequisites.sh should work properly. Trying to install manually or modifying OME's sources will not help solve your problem.

Run it with Docker or try prerequisites.sh .

**Comment by danrossi** [comment]
I already ran prerequisites, that was the first failure, it seems some of the missing includes is because of prefix variable problems within that script and then gets installed in default locations. This include is non existent in the openssl install. 

```
[  1/352|  0%] Preparing directories...
[  2/352|  0%] [static] libovcrypto.a: C++ projects/base/ovcrypto/certificate.cpp => intermediates/RELEASE/objs/base/ovcrypto/certificate.o
projects/base/ovcrypto/certificate.cpp:3:10: fatal error: openssl/core_names.h: No such file or directory
    3 | #include <openssl/core_names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
```

```
/opt/ovenmediaengine/include/openssl$ ls
aes.h       buffer.h     crypto.h     ec.h         kdferr.h      opensslconf.h  randerr.h    ssl.h       ui.h
asn1.h      buffererr.h  cryptoerr.h  ecdh.h       lhash.h       opensslv.h     rc2.h        ssl2.h      uierr.h
asn1_mac.h  camellia.h   ct.h         ecdsa.h      md2.h         ossl_typ.h     rc4.h        ssl3.h      whrlpool.h
asn1err.h   cast.h       cterr.h      ecerr.h      md4.h         pem.h          rc5.h        sslerr.h    x509.h
asn1t.h     cmac.h       des.h        engine.h     md5.h         pem2.h         ripemd.h     stack.h     x509_vfy.h
async.h     cms.h        dh.h         engineerr.h  mdc2.h        pemerr.h       rsa.h        store.h     x509err.h
asyncerr.h  cmserr.h     dherr.h      err.h        modes.h       pkcs12.h       rsaerr.h     storeerr.h  x509v3.h
bio.h       comp.h       dsa.h        evp.h        obj_mac.h     pkcs12err.h    safestack.h  symhacks.h  x509v3err.h
bioerr.h    comperr.h    dsaerr.h     evperr.h     objects.h     pkcs7.h        seed.h       tls1.h
blowfish.h  conf.h       dtls1.h      hmac.h       objectserr.h  pkcs7err.h     sha.h        ts.h
bn.h        conf_api.h   e_os2.h      idea.h       ocsp.h        rand.h         srp.h        tserr.h
bnerr.h     conferr.h    ebcdic.h     kdf.h        ocsperr.h     rand_drbg.h    srtp.h       txt_db.h
```

**Comment by getroot** [comment]
Execute prerequisites.sh and capture the failure log from there and upload it. It seems that it would be easy to solve the problem.

**Comment by getroot** [comment]
We recently upgraded the OPENSSL version to 3.x. If you run prerequisites.sh from an old release and compile code from the dev branch, it may fail. To compile the dev branch, you must run the prerequisites.sh of the dev branch.

**Comment by danrossi** [comment]
I was susccessful after 6 rebuilds running under sudo. I had a fault at FDK. So had to comment out the builds up to that. 

```
sudo misc/prerequisites.sh
```

I'm sorry I don't know what what was going. I have a service loaded but no connectable ports like in my Debian system.
